# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: gcsfuse | Add Google Cloud gcsfuse repo
  yum_repository:
    name: gcsfuse
    description: Google cloud gcsfuse    
    baseurl: https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: true
  when: ansible_os_family == "RedHat"

- name: gcloud | Install latest gcloud gcsfuse package
  package:
    name: gcsfuse
    state: present
    lock_timeout: "{{ pkg_mgr_lock_timeout }}"
  when: ansible_os_family == "RedHat"
