project_id            = "mock-project-id"
region                = "europe-west3"
zone                  = "europe-west3-a"
bucket_name           = "mock-zdm-migration-bucket"
zdm_software_bucket   = "mock-zdm-software-bucket"
zdm_software_zip      = "zdm_software.zip"
ssh_public_key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD..."
source_db_ips         = ["10.10.1.5"]
target_db_ips         = ["10.20.1.10"]
exacs_target_node_ips = ["10.152.1.11", "10.152.1.12"]
dbcs_target_db_ips    = ["10.154.1.5"]
adb_target_endpoint   = "mock_db_high"
zdm_image             = "gcr.io/mock-project/zdm:latest"
ssh_private_key       = "-----BEGIN RSA PRIVATE KEY-----\nMOCK\n-----END RSA PRIVATE KEY-----"
deploy_goldengate     = false
ogg_image             = "container-registry.oracle.com/database/goldengate:latest"
u01_disk_size         = 100
data_disk_size        = 200
reco_disk_size        = 100
target_type           = "gce"
install_docker        = false
