apiVersion: v1
kind: Namespace
metadata:
  name: zdm-migration
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zdm-k8s-sa
  namespace: zdm-migration
  annotations:
    iam.gke.io/gcp-service-account: zdm-gke-sa@PROJECT_ID.iam.gserviceaccount.com
