- name: ar_repo_setup | Setup Artifact Registry mirrors
  become: true
  block:
    - name: ar_repo_setup | Disable all repositories to prevent timeouts
      command: "dnf config-manager --set-disabled *"

    - name: ar_mirror_setup | Re-enable google-compute-engine google-cloud-sdk repositories (via PGA)
      # This preserves the Guest Agent and other critical GCP services
      command: "dnf config-manager --set-enabled google-compute-engine google-cloud-sdk"
      failed_when: false

    - name: ar_repo_setup | Install Artifact Registry DNF plugin
      package:
        name: dnf-plugin-artifact-registry
        state: present

    - name: ar_repo_setup | Configure project-specific mirrors
      yum_repository:
        name: "ar-{{ item }}"
        description: "Internal Artifact Registry repository for {{ item }}"
        baseurl: "{{ ar_repo_url }}-{{ item }}"
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: no
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"
        priority: "1"
      loop:
        - baseos
        - appstream

  when:
    - ansible_distribution == 'OracleLinux'
  tags: os_packages
