# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: sql_patch | SID confirmation
  debug:
    msg: "Running post patch operations for SID: {{ oracle_sid }}"
    verbosity: 0

- name: sql_patch | Set default upgrade mode
  set_fact:
    startup_upgrade: ""
  when: not patch.upgrade | bool

- name: sql_patch | Determine if upgrade mode is required
  set_fact:
    startup_upgrade: "upgrade"
  when: patch.upgrade | bool

- name: sql_patch | Start DB
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<< "startup {{ startup_upgrade }};"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  register: startup_db
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms,upgrade-db

- name: sql_patch | DB Startup output
  debug:
    msg: "{{ startup_db }}"
    verbosity: 1
  tags: patch-rdbms,upgrade-db

- name: sql_patch | Start all PDBs
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<< "alter pluggable database all open {{ startup_upgrade }};"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  register: startup_pdb
  ignore_errors: true
  become: true
  become_user: "{{ oracle_user }}"
  when: oracle_ver != '11.2.0.4.0'
  tags: patch-rdbms,start-pdb

- name: sql_patch | Start PDBs output
  debug:
    msg: "{{ startup_pdb }}"
    verbosity: 1
  when: oracle_ver != '11.2.0.4.0'

- name: sql_patch | Run datapatch
  shell: |
    {{ oracle_home }}/OPatch/datapatch -verbose
  environment:
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_HOME: "{{ oracle_home }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  when: oracle_ver != '11.2.0.4.0'
  register: datapatch_output
  failed_when: "datapatch_output.rc != 0"
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms,datapatch

- name: sql_patch | datapatch results
  debug:
    msg: "{{ datapatch_output }}"
    verbosity: 1
  when: oracle_ver != '11.2.0.4.0'
  tags: patch-rdbms,datapatch

- name: sql_patch | Run catbundle
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<< "@catbundle.sql psu apply"
  args:
    chdir: "{{ oracle_home }}/rdbms/admin"
  environment:
    ORACLE_SID: "{{ oracle_sid }}"
    ORACLE_HOME: "{{ oracle_home }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  when: oracle_ver == '11.2.0.4.0'
  register: catbundle_output
  failed_when: "catbundle_output.rc != 0"
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms,catbundle

- name: sql_patch | catbundle results
  debug:
    msg: "{{ catbundle_output }}"
    verbosity: 1
  when: oracle_ver == '11.2.0.4.0'
  tags: patch-rdbms,catbundle

- name: sql_patch | Re-compile invalid objects
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<< "@?/rdbms/admin/utlrp;"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms,utlrp

- name: sql_patch | Capture registry patches
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba << EOF
    set pages 0 lines 200
    col action_time for a28
    col action for a10
    col status for a10
    select action_time, action, status, patch_id from dba_registry_sqlpatch order by action_time;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  when: oracle_ver != '11.2.0.4.0'
  register: patch_registry
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms

- name: sql_patch | Registry patch results
  debug:
    msg: "{{ patch_registry }}"
    verbosity: 0
  when: oracle_ver != '11.2.0.4.0'

- name: sql_patch | Shutdown DB
  shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<< "shutdown immediate"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
  register: shutdown_db
  become: true
  become_user: "{{ oracle_user }}"
  tags: patch-rdbms,upgrade-db

- name: sql_patch | Shutdown DB results
  debug:
    msg: "{{ shutdown_db }}"
    verbosity: 1
  tags: patch-rdbms,upgrade-db
