# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Install Google Cloud Agent for Compute Workloads
  include_tasks:
    file: install.yml
  tags: workload-agent

- name: Fetch agent password and create database user
  include_tasks:
    file: create_db_user.yml
  when:
    - oracle_metrics_secret | length > 0
  tags: workload-agent
