# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: populate-vars | Resolve software release
  set_fact:
    oracle_rel: "{{ found_rel | trim }}"
  vars:
    found_rel: >-
      {% if oracle_rel == "latest" %}
        {{ (gi_patches | selectattr('base', 'equalto', oracle_ver) | list | last | default({})).release | default('base') }}
      {% else %}
        {% set matched_patch = gi_patches | selectattr('base', 'equalto', oracle_ver) | selectattr('release', 'equalto', oracle_rel) | list | first %}
        {{ matched_patch.release | default((gi_patches | selectattr('base', 'equalto', oracle_ver) | list | last | default({})).release) if matched_patch is defined else (gi_patches | selectattr('base', 'equalto', oracle_ver) | list | last | default({})).release }}
      {% endif %}
  when:
    - not free_edition
    - oracle_rel is defined
    - oracle_rel != "base"
  tags: oracle-rel

- name: populate-vars | Resolve Free Edition software release
  set_fact:
    oracle_ver: "{{
      (oracle_rel == 'latest') and (free_versions | last) or
      (oracle_rel == 'base') and (free_versions | first) or
      (oracle_rel in free_versions) and oracle_rel or
      (free_versions | last)
    }}"
  vars:
    free_versions: "{{ rdbms_software | selectattr('edition', 'equalto', 'FREE') | map(attribute='version') | sort | list }}"
  when:
    - free_edition
    - oracle_ver == "23.0.0.0.0"
  tags: oracle-rel

- name: populate-vars | Show resolved release
  debug:
    var: oracle_rel
    verbosity: 0
  tags: oracle-rel
