# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: gcsdirect | Copy OPatch
  shell: |
    set -o pipefail
    gcloud storage cp "gs://{{ swlib_mount_src }}/{{ item }}" "{{ swlib_path }}/{{ item }}"
  register: shell_result
  args:
    executable: /bin/bash
  with_items: "{{ opatch_file_list | unique }}"
  changed_when: "'Date    Time    Name' not in shell_result.stdout"

- name: gcsdirect | Copy base software files using file_name or alt_name
  shell: |
    set -o pipefail
    if gcloud storage ls "gs://{{ swlib_mount_src }}/{{ item.file_name }}" >/dev/null 2>&1; then
      f_name="{{ item.file_name }}"
    else
      f_name="{{ item.alt_name | default('x') }}"
    fi
    if ! unzip -l "{{ swlib_path }}/${f_name}"; then
      gcloud storage cp "gs://{{ swlib_mount_src }}/${f_name}" "{{ swlib_path }}/{{ item.file_name }}"
    fi
  register: shell_result
  args:
    executable: /bin/bash
  with_items: "{{ base_sw_file_list | unique }}"
  changed_when: "'Date    Time    Name' not in shell_result.stdout"

- name: gcsdirect | Copy patch files
  shell: |
    set -o pipefail
    if ! unzip -l "{{ swlib_path }}/{{ item }}"
      then
        gcloud storage cp "gs://{{ swlib_mount_src }}/{{ item }}" "{{ swlib_path }}/{{ item }}"
    fi
  register: shell_result
  args:
    executable: /bin/bash
  with_items: "{{ patch_file_list | unique }}"
  changed_when: "'Date    Time    Name' not in shell_result.stdout"

- name: gcsdirect | Download or copy RPM software from GCS to target instance
  shell: |
    set -o pipefail
    {% for f in item.files %}
    if ! rpm -qp "{{ swlib_path }}/{{ f.name | basename }}"; then
      if [[ "{{ f.name }}" == https://*oracle.com/* || "{{ f.name }}" == http://*oracle.com/* ]]; then
        curl --location --silent --connect-timeout 20 --fail -o "{{ swlib_path }}/{{ f.name | basename }}" "{{ f.name }}" && echo "File downloaded"
      else
        gcloud storage cp "gs://{{ swlib_mount_src }}/{{ f.name }}" "{{ swlib_path }}/{{ f.name }}" && echo "File copied"
      fi
    fi
    {% endfor %}
  register: shell_result
  args:
    executable: /bin/bash
  with_items: "{{ rdbms_software }}"
  when:
    - item.version == oracle_ver
    - free_edition
  changed_when: '"File downloaded" in shell_result.stdout or "File copied" in shell_result.stdout'
